[package]
name = "zikzakzoo_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
zikzakzoo-core = { path = "../../core" }
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
